# Generated by Django 5.0.6 on 2024-08-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="slug",
        ),
    ]
