# Generated by Django 5.0.6 on 2024-08-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_review_review_rating_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
